---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 29456.
--- DateTime: 2025/3/20 19:50
---

-- 锁的Key "lock:order:5"
-- local key = KEYS[1]
-- 当前线程标识 "skdfhskdjf-33"
-- local threadId = ARGV[1]

-- 获取锁中的线程标识 get key
local id = redis.call('get', KEYS[1])
-- 比较线程标识与锁中的标识是否一致
if (id == ARGV[1]) then
    -- 释放锁 del key
    return redis.call('del', KEYS[1])
end
return 0